//! The system's DNS servers and search domains, which unicast DNS-SD browses in: a
//! facility's DNS server can list its NMOS registry where multicast DNS does not reach,
//! across subnets (IS-04 §3).

use std::net::{IpAddr, SocketAddr};

/// Where the system lists them, on Linux and macOS alike.
const RESOLV_CONF: &str = "/etc/resolv.conf";

/// The DNS servers and search domains that resolv.conf text names. Of `domain` and
/// `search`, the last one given counts, as the resolver reads them.
pub fn parse(text: &str) -> (Vec<SocketAddr>, Vec<String>) {
    let mut servers = Vec::new();
    let mut domains = Vec::new();
    for line in text.lines() {
        let line = line.split(['#', ';']).next().unwrap_or_default();
        let mut words = line.split_whitespace();
        match words.next() {
            Some("nameserver") => {
                // A link-local IPv6 server may carry its zone, which a socket address cannot.
                let address = words.next().map(|w| w.split('%').next().unwrap_or(w));
                if let Some(ip) = address.and_then(|a| a.parse::<IpAddr>().ok()) {
                    servers.push(SocketAddr::new(ip, 53));
                }
            }
            Some("domain" | "search") => {
                domains = words.map(|d| d.trim_end_matches('.').to_string()).filter(|d| !d.is_empty()).collect();
            }
            _ => {}
        }
    }
    // Multicast DNS answers for .local, not a DNS server.
    domains.retain(|d| !d.eq_ignore_ascii_case("local"));
    (servers, domains)
}

/// The system's DNS servers and search domains, or none where it lists none.
pub fn system() -> (Vec<SocketAddr>, Vec<String>) {
    std::fs::read_to_string(RESOLV_CONF).map(|text| parse(&text)).unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reads_servers_and_the_last_search_line() {
        let text = "# Generated by NetworkManager\n\
                    domain old.example\n\
                    search studio.example. broadcast.example local\n\
                    nameserver 192.168.10.1\n\
                    nameserver fe80::1%en0 ; the router\n\
                    nameserver not-an-address\n\
                    options edns0\n";
        let (servers, domains) = parse(text);
        assert_eq!(servers, ["192.168.10.1:53".parse().unwrap(), "[fe80::1]:53".parse().unwrap()]);
        assert_eq!(domains, ["studio.example", "broadcast.example"]);
        assert_eq!(parse(""), (vec![], vec![]));
    }
}
